[phases.setup]
nixPkgs = [
    'python39',
    'python39-pip',
    'python39.dev',
    'gcc',
    'postgresql',  # This provides libpq
    'python3.dev',
    'musl'
]

[phases.install]
cmds = [
    'pip install -r requirements.txt'
]

[start]
cmd = "gunicorn --worker-tmp-dir /dev/shm app:app"
