[phases.setup]
nixPkgs = [
    'python39',
    'python39.pkgs.pip',
    'gcc',
    'postgresql',
    'python39.pkgs.setuptools',
    'musl'
]

[phases.install]
cmds = [
    'pip install -r requirements.txt'
]

[build]
nixLayers = false

[start]
cmd = "gunicorn --worker-tmp-dir /dev/shm app:app"
